server:
  port: ${PORT:8086}
spring:
  application:
    name: relex-market
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/market}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123321}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 8
  mail:
    host: smtp.gmail.com
    port: 587
    username: smetaninIvanU@gmail.com
    password: axyesxomvimgqcok
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  liquibase:
    change-log: classpath:db/migration/v1/changelog.yaml
  jackson:
    mapper:
      accept-case-insensitive-enums: true
    property-naming-strategy: SNAKE_CASE
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
logging:
  level:
    ru.relex.market: debug